### PR TITLE
feat: Update alert styling and remove size prop

### PR DESCRIPTION
**Pull request by cillascillas**
After a [design review, new updates related to styling](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/Design-System?node-id=5314%3A1401) are coming:

- Title font-size -> 20px
- Body font-size -> 16px
- Link styling (depending on alert type, underlined by default, not underlined in hover)
- Remove alert size prop:
    - Type prop would be removed.
    - Default size would be current medium. (It only affects to padding size)
- Add new doc

### CODE REVIEW

**Comment by afontcu** [comment]
We could also remove the `size` prop, right? 🔥🔥🔥 🚒

**Comment by cillascillas** [comment]
@afontcu 🤦‍♀️ sure, my bad! That was the reason for the PR in the first place!

**Review by afontcu — APPROVED** [review]
🚀 🔥

**Review by alexcastelo95 — APPROVED** [review]
🚀

**Pull request merged**
