### PR TITLE
feat: Add Car and ElectricCar pictos

### PR DESCRIPTION
**Pull request by alex-castelo**
# Context
We have added with Iban these 2 pictos and their variants while documenting the process for everyone.

This PR is related to this one [holaluz/assets - feature: add Car and Electric Car Pictos](https://github.com/holaluz/assets/pull/24)

### CODE REVIEW

**Comment by sergigraciaj** [comment]
We have to add the names to https://github.com/holaluz/margarita/blob/472bac2b715df181dfabb5180870a3493308e3f5/src/components/MaPicto/MaPicto.vue#L32
Could you do a little fix for me, please? Add an 's' to the end of https://github.com/holaluz/margarita/blob/472bac2b715df181dfabb5180870a3493308e3f5/src/components/MaPicto/availablePictos.ts#L9 so it's `SolarPanels`

**Comment by alex-castelo** [comment]
> We have to add the names to
> 
> https://github.com/holaluz/margarita/blob/472bac2b715df181dfabb5180870a3493308e3f5/src/components/MaPicto/MaPicto.vue#L32
> 
> 
> Could you do a little fix for me, please? Add an 's' to the end of
> https://github.com/holaluz/margarita/blob/472bac2b715df181dfabb5180870a3493308e3f5/src/components/MaPicto/availablePictos.ts#L9
> 
> so it's `SolarPanels`

Of course 😄

**Review by edufarre — APPROVED** [review]

**Review by sergigraciaj — APPROVED** [review]
Remember to update vetur attributes.json! 🚀

**Pull request merged**
