### PR TITLE
feat: Remove headerType prop from modal

### LINKED ISSUE #491: [MaModal] Remove gradient header
The gradient header is not accessible anymore. Let's remove it.

### PR DESCRIPTION
**Pull request by carlotamolintr**
Closes #491

### CODE REVIEW

**Review by edufarre — COMMENTED** [review]
Isn't this a Breaking Change?

**Comment by carlotamolintr** [comment]
> Isn't this a Breaking Change?

Yes! You're right! I'm going to change the semantic realease now

**Review by Samitier — APPROVED** [review]
nice 😄

**Review by alex-castelo — APPROVED** [review]
Good work!

**Pull request merged**
