### PR TITLE
fix: scope styles in MaAlert 

### PR DESCRIPTION
**Pull request by carlotamolintr**
Hi all,
This PR is to scope the styles from Ma-alert #401  because we are overlapping other component styles (as the RadioQuestions commented on the [issue before](https://github.com/holaluz/margarita/issues/409)). Also, I removed the tag defined previously to fix the MaOption because is not doing anything it should be solved with this fix.

### CODE REVIEW

**Review by Samitier — APPROVED** [review]
nice! Is it a breaking change? Does anybody have `.icon` or `.alert` classes in their projects?

**Comment by afontcu** [comment]
I'd define "using internal classes" it as relying on internals of the library, which can change change without further notice 😄  So I'd suggest issuing a patch or minor release, not a breaking change

**Review by edufarre — APPROVED** [review]

**Comment by carlotamolintr** [comment]
Should I wait or I can merge this?

**Comment by sergigraciaj** [comment]
U can merge it! : )

**Comment by afontcu** [comment]
> Should I wait or I can merge this?

Feel free to merge it! Remember to give it a proper commit merge name. "Using internal classes" do not explain what are we fixing here! ;)

**Pull request merged**
