### PR TITLE
fix: Fix alignment when using MaText and input components

### PR DESCRIPTION
**Pull request by afontcu**
…to fix alignment when used in conjunction with other MaText components. Related to https://holaluz.slack.com/archives/CR9670R5H/p1614869238064300

- [x] Update MaTextField
- [x] Update MaSelect
- [x] Update MaRange

### CODE REVIEW

**Comment by afontcu** [comment]
not sure if `feat` or `fix` 🤷‍♀️

**Review by edufarre — APPROVED** [review]

**Comment by edufarre** [comment]
> not sure if `feat` or `fix` 🤷‍♀️

I do believe this is a `fix`, as it fixes (good redundancy here) the displayed text styles/appearance

**Comment by afontcu** [comment]
> I do believe this is a `fix`, as it fixes (good redundancy here) the displayed text styles/appearance and we are not delivering any new feature or something that did not have before this PR, right?

One could say that the PR adds the ability to work in conjunction with MaText 😄 that being said, totally ok with a fix release 😉 updating the title

Moreover, let's talk about this in our next meeting. We could simplify things by only releasing minor versions and forgetting about the distinction between minor and patch

**Comment by edufarre** [comment]
> One could say that the PR adds the ability to work in conjunction with MaText 😄 that being said, totally ok with a fix release 😉 updating the title

just gave my point of view, didn't say it was the correct one 😞  I did not think about the approach you said, although I reckon it makes 100% sense.

**Pull request merged**
