### PR TITLE
fix: fix ma option error icon

### PR DESCRIPTION
**Pull request by Samitier**
I was trying to use the errored checkbox in `maitai` but the error icon doesn't load. I don't know if this fixes it but hopefully the svg wil be imported inline and solve the problem.

image

### CODE REVIEW

**Review by sergigraciaj — APPROVED** [review]

**Review by edufarre — APPROVED** [review]

**Comment by Samitier** [comment]
it doesn't work 😂

**Comment by edufarre** [comment]
> it doesn't work 😂

wtf!

**Comment by Samitier** [comment]
I'm going to do it with a `background -mage` like the icon in `ma-text-field`. Seems like webpack inlines those but not `` 🤷‍♂️

**Pull request merged**
