### PR TITLE
feat: Change MaHeading sizes for tablet

### PR DESCRIPTION
**Pull request by carlotamolintr**
[BREAKING CHANGE]: change ma-heading sizes for tablet

### CODE REVIEW

**Review by cillascillas — APPROVED** [review]
💪

**Comment by cillascillas** [comment]
But if we want to make a "breaking change" we should change the PR title to "feat: change MaHeading sizes for tablet"

**Comment by carlotamolintr** [comment]
> But if we want to make a "breaking change" we should change the PR title to "feat: change MaHeading sizes for tablet"

Thank you 🙏

**Review by edufarre — APPROVED** [review]

**Pull request merged**
