### PR TITLE
fix: add declarations file

### PR DESCRIPTION
**Pull request by sergigraciaj**
Add TS declarations file in order to work as a plugin in projects with Typescript.
Not sure why we had a margarita declaration file with Layout and Breakpoint types.
Our package points to index.d.ts https://github.com/holaluz/margarita/blob/2bda992f94550e1788577e6ccacf24dab618426d/package.json#L11

### CODE REVIEW

**Review by alex-castelo — COMMENTED** [review]
I'm not sur if I understand. This new file is the one that our npm package points as a `TS declaration file` , right?

**Comment by sergigraciaj** [comment]
That's it : )

**Review by alex-castelo — APPROVED** [review]
🔝

**Pull request merged**
